config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#index"
  resources :users, only: [:index, :create, :destroy]
  resources :main_recipes
  resources :foods, except: [:show]
  resources :recipes
  resources :recipe_foods, only: [:update, :edit, :new, :create, :destroy]

  get '/public_recipes', to: 'public_recipes#index', as: "public_recipes"
  get '/general_shopping_lists', to: 'general_shopping_lists#index', as: "general_shopping_lists"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :manage, Food, user_id: user.id
      can :manage, Recipe, user_id: user.id
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods, dependent: :destroy
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods, dependent: :destroy

  validates :name, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy
  has_many :recipe_foods, through: :recipes

  validates_presence_of :name, :email, :password

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[edit update destroy]
  before_action :authenticate_user!

  def index
    @foods = Food.all
    @food = Food.new
  end

  def new
    @food = Food.new
  end

  def edit; end

  def create
    @food = Food.new(food_params)
    @food.user = current_user

    if @food.save
      redirect_to foods_path, notice: 'Food successfully created.'
    else
      render :new
    end
  end

  def update
    if @food.update(food_params)
      redirect_to foods_url, notice: 'Food was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path, notice: 'Food deleted successfully.'
  end

  private

  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/general_shopping_lists_controller.rb
class GeneralShoppingListsController < ApplicationController
  def index
    @recipe_foods = RecipeFood.includes(:food)
    @food_count = RecipeFood.select(:food_id).distinct.count
  end
end

app/controllers/main_recipes_controller.rb
class MainRecipesController < ApplicationController
  before_action :set_recipe, only: %i[show destroy update edit]
  before_action :authenticate_user!

  def index
    @recipes = Recipe.includes(:user).where(user_id: current_user.id)
  end

  def show
    @food = Food.all
    @recipe_food = RecipeFood.includes(:food)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      redirect_to main_recipe_path(@recipe), notice: 'Recipe was created successfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @recipe.update(recipe_params)
      redirect_to main_recipe_path(@recipe), notice: 'Your recipe is set to public successfully'
    else
      redirect_to main_recipe_path(@recipe), notice: 'Something went wrong your recipe is not updated'
    end
  end

  def destroy
    if @recipe.destroy
      redirect_to main_recipes_path, notice: 'Recipe was successfully deleted'
    else
      redirect_to main_recipe_path(@recipe), notice: 'Something wrong happened recipe is not deleted'
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.where(public: true)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
    @foods = Food.all
    @recipes = Recipe.all
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    if @recipe_food.save
      redirect_to main_recipes_url, notice: 'Recipe food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @recipes = Recipe.all
    @foods = Food.all
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])

    if @recipe_food.update(recipe_food_params)
      redirect_to main_recipe_path(@recipe_food.recipe), notice: 'Recipe food item was updated successfully'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])

    if @recipe_food.destroy
      redirect_to main_recipe_url, notice: 'Recipe food was successfully deleted'
    else
      redirect_to main_recipe_url, notice: 'Recipe food is not deleted'
    end
  end

  private

  def set_recipe_foods
    @recipe_food = RecipeFood.find(params[:id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:recipe_id, :food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @recipes = Recipe.all
  end

  def show; end

  def new
    @recipe = Recipe.new
  end

  def edit; end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_key)
    case flash_key
    when 'success'
      'success'
    when 'alert'
      'danger'
    else
      'info'
    end
  end
end

app/views/foods/index.html.erb
<section class="container mt-5">
  <div class="d-flex justify-content-between mb-3 align-items-center">
    <h1 class="text-center flex-grow-1">Food list</h1>
    <%= link_to "Add Food", new_food_path, class: "btn btn-primary float-right" %>
  </div>

  <div class="text-center">
    <table class="table table-striped custom-table">
      <thead>
      <tr>
        <th>Food</th>
        <th>Measurement Unit</th>
        <th>Unit Price&nbsp;$</th>
        <th>Action</th>
      </tr>
      </thead>
      <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= food.price %></td>
          <td>
            <%= button_to "Delete", food, method: :delete, data: { confirm: "Are you sure you want to delete this food?" }, class: "btn btn-danger btn-sm" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

</section>

app/views/foods/new.html.erb
<h1>Add Food</h1>

<%= form_with(model: @food, url: foods_path, class: "food-form") do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :measurement_unit %>
    <%= form.text_field :measurement_unit, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text">$</span>
      </div>
      <%= form.number_field :price, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: "form-control" %>
  </div>

  <div class="actions d-flex justify-content-end mb-3">
    <%= form.submit "Add Food", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Back", foods_path, class: "btn btn-secondary" %>

app/views/general_shopping_lists/index.html.erb
<section class="container mt-5">
  <h1 class="text-center mb-3">Shopping list</h1>

  <div class="d-flex justify-content-around">
    <p>Amount of food items to buy: <%= @food_count %></p>
    <% food_quantities_prices = @recipe_foods.map { |food| food.quantity * food.food.price } %>
    <p>Total value of food needed: <%= number_to_currency(food_quantities_prices.sum) %> </p>
  </div>

  <div class="text-center">
    <table class="table table-striped custom-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
      <% @recipe_foods.group_by{|food| food.food.name}.each do |name, foods| %>
        <tr>
          <td><%= name %></td>
          <td><%= foods.sum(&:quantity) %></td>
          <td><%= number_to_currency(foods.first.food.price * foods.sum(&:quantity))%></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg bg-body-tertiary bg-secondary">
    <div class="container-fluid">
      <%= link_to "Recipe App",  root_path, class: "navbar-brand text-white" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Foods", foods_path, class: "nav-link active text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Recipes", main_recipes_path, class: "nav-link active text-white" %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to "Public Recipes", public_recipes_path, class: "nav-link active text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Shopping list", general_shopping_lists_path, class: "nav-link active text-white" %>
          </li>
        </ul>
        <% if user_signed_in?%>
          <div class="d-flex align-items-center gap-3">
            <p class="m-0 text-white">Logged in as <%= current_user.email %></p>
            <%= button_to "Log out", destroy_user_session_path, method: :delete %>
          </div>
        <%else%>
          <%= link_to "Log in", new_user_session_path %> |
          <%= link_to "Sign up", new_user_registration_path %>
        <%end%>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" defer></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= bootstrap_class_for(key) %>">
      <%= value %>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/main_recipes/_toggle_btn.html.erb
<%= form_with url: main_recipe_path(@recipe), model: @recipe, data: { turbo_method: :put, turbolinks: true }, id: "toggle-btn-form" do | f | %>
  <div class="form-check form-switch">
    <%= f.check_box :public, class: 'form-check-input', role: "switch", id: "flexSwitchCheckDefault" %>
    <%= f.label :public, class: 'form-check-label', for: 'flexSwitchCheckDefault' do %>
      Public
    <% end %>
  </div>
<% end %>

app/views/main_recipes/edit.html.erb
<h1 class="text-center mb-5">Edit Recipe</h1>

<%= form_with(model: @recipe, url: main_recipe_path(@recipe), class: "container", method: :put) do | form | %>
  <div class="input-group mb-3">
    <%= form.text_field :name, class: "form-control", placeholder: "Enter name", required: true %>
  </div>

  <div class="input-group mb-3">
    <%= form.text_field :preparation_time, class: "form-control", placeholder: "Enter preparation time example: '00hrs:05min:00sec'", required: true %>
  </div>

  <div class="input-group mb-3">
    <%= form.text_field :cooking_time, class: "form-control", placeholder: "Enter cooking time example: '00hrs:05min:00sec'", required: true %>
  </div>

  <div class="input-group mb-3">
    <%= form.text_field :description, class: "form-control", placeholder: "Enter price", required: true %>
  </div>

  <div class="form-check form-switch mb-3">
    <%= form.check_box :public, class: 'form-check-input', role: "switch", id: "flexSwitchCheckDefault", required: true %>
    <%= form.label :public, class: 'form-check-label', for: 'flexSwitchCheckDefault' do %>
      Public
    <% end %>
  </div>

  <div>
    <%= form.submit "Save Edit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/main_recipes/index.html.erb
<section id="recipes" class="container text-center mt-5">
  <div class="mb-4 d-flex justify-content-between align-items-center">
    <h1 class="m-0">Recipes list</h1>
    <%= link_to "Create new recipe", new_main_recipe_path, class: "btn btn-primary" %>
  </div>

  <div>
    <ul class="list-unstyled">
      <% @recipes.each do | recipe | %>
        <li class="d-flex align-items-start column-gap-3 mb-3 border border-primary border-2 p-2">
          <div class="d-flex flex-column align-items-start row-gap-2">
            <%= link_to main_recipe_path(recipe), class: "recipe-title text-decoration-none p-2 px-3" do %>
              <h2 class="bold fs-5 m-0"><%= recipe.name.capitalize %></h2>
            <% end %>
            <% if can? :manage, recipe %>
              <%= link_to "Remove", main_recipe_path(recipe), class: "recipe-title p-2 px-3",data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{recipe.name.capitalize} recipe" } %>
            <% end %>
          </div>

          <div class="p-2 ps-0">
            <p class="m-0 text-start">
              <%= recipe.description %>
            </p>
          </div>
        </li>
      <% end %>
    </ul>
  </div>

</section>

app/views/main_recipes/new.html.erb
<section class="mt-5">
  <h1 class="text-center mb-5">Create Recipe</h1>

  <%= form_with(model: @recipe, url: main_recipes_path(@recipe),class: "container", method: :post) do |form| %>
    <div class="input-group mb-3">
      <%= form.text_field :name, class: "form-control", placeholder: "Enter name", required: true %>
    </div>

    <div class="input-group mb-3">
      <%= form.text_field :preparation_time, class: "form-control", placeholder: "Enter preparation time example: '00hrs:05min:00sec'", required: true %>
    </div>

    <div class="input-group mb-3">
      <%= form.text_field :cooking_time, class: "form-control", placeholder: "Enter cooking time example: '00hrs:05min:00sec'", required: true %>
    </div>

    <div class="input-group mb-3">
      <%= form.text_area :description, class: "form-control", placeholder: "Enter description", required: true, size: "70x5" %>
    </div>

    <div class="form-check form-switch mb-3">
      <%= form.check_box :public, class: 'form-check-input', role: "switch", id:"flexSwitchCheckDefault" %>
      <%= form.label :public, class: 'form-check-label', for: 'flexSwitchCheckDefault' do %>
        Public
      <% end %>
    </div>

    <div>
      <%= form.submit "Create recipe", class: "btn btn-primary" %>
    </div>
  <% end %>
</section>

app/views/main_recipes/show.html.erb
<section id="recipe" class="container mt-5">
  <h1 class="text-center"><%= @recipe.name.capitalize %></h1>
  <div>
    <div class="d-flex justify-content-between mb-3">
      <span>Preparation time: <%= @recipe.preparation_time %></span>
      <% if can? :manage, @recipe %>
        <%= render 'toggle_btn' %>
      <% end %>
    </div>

    <span class="mb-3 d-block">Cooking time: <%= @recipe.cooking_time %></span>
    <p>
      <%= @recipe.description %>
    </p>

    <div class="d-flex justify-content-between mb-5">
      <%= link_to "Generate shopping list", general_shopping_lists_path, class: "btn btn-primary" %>
      <% if can? :manage, @recipe %>
        <%= link_to "Add ingredients", new_recipe_food_path, class: "btn btn-primary" %>
      <% end %>
    </div>

    <div class="text-center">
      <table class="table table-striped custom-table">
        <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <% if can? :manage, @recipe %>
            <th>Actions</th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% @recipe_food.each do | item | %>
          <% if @recipe.id == item.recipe_id %>
            <tr>
              <td><%= item.food.name %></td>
              <td>
                <span>
                  <%= item.quantity %>
                </span>
                <span>
                  <%= item.food.measurement_unit %>
                </span>
              </td>
              <td>$<%= item.quantity * item.food.price %></td>
              <% if can? :manage, @recipe %>
                <td>
                  <div class="d-flex align-items-center justify-content-center gap-1">
                    <%= button_to "Remove", item, method: :delete, data: { turbo_confirm: "Are you sure you want to delete food item?" }, class: "btn btn-danger btn-sm" %>
                    <%= link_to "Modify", edit_recipe_food_path(item), class: "btn btn-primary btn-sm" %>
                  </div>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <% if can? :manage, @recipe %>
    <div class="d-flex align-items-center gap-2">
      <%= button_to "Delete Recipe", main_recipe_path(@recipe), method: :delete, data: {turbo_confirm: "Are you sure you want to delete this Recipe"}, class: "btn btn-danger" %>
      <%= link_to "Edit Recipe", edit_main_recipe_path(@recipe), class: "btn btn-primary" %>
    </div>
  <% end %>
</section>

<%= javascript_importmap_tags 'controllers/main_recipes/show' %>

app/views/public_recipes/index.html.erb
<section class="mt-5">
  <div class="container">
    <div class="row justify-content-center mb-4">
      <div class="col-md-8 text-center">
        <h1 class="display-4">Public Recipes</h1>
      </div>
    </div>

    <div class="row">
      <% @recipes.each do |recipe| %>
        <div class="col-md-12 mb-3">
          <div class="card" style="width: 100%;">
            <div class="card-body">
              <div class="d-flex justify-content-between">
                <h2 class="card-title"><%= recipe.name %></h2>
                <div>
                  <p class="card-text">Food Items: <%= recipe.foods.count %></p>
                  <p class="card-text">Total Price: $<%= recipe.foods.sum(:price) %></p>
                </div>
              </div>
              <p class="card-text">Prepared by: <%= recipe.user.name %></p>
              <%= link_to 'View Recipe',  main_recipe_path(recipe), class: 'btn btn-primary mt-auto' %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</section>

app/views/recipe_foods/edit.html.erb
<h1 class="text-center mb-5">Edit Food item</h1>

<%= form_with(model: @recipe_food,class: "container", method: :put) do |form| %>
  <div class="field">
    <%= form.label :recipe_id, style: "display: block", class: "label" %>
    <%= form.select :recipe_id, @recipes.map { |recipe| [recipe.name, recipe.id] } %>
  </div>

  <div class="field">
    <%= form.label :food_id, style: "display: block", class: "label" %>
    <%= form.select :food_id, @foods.map { |food| [food.name, food.id] } %>
  </div>

  <div class="field">
    <%= form.label :quantity, style: "display: block", class: "label" %>
    <%= form.number_field :quantity, required: true, class:"input" %>
  </div>

  <div>
    <%= form.submit "Save Edit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recipe_foods/new.html.erb
<h1 class="text-center mb-5">Add Food item</h1>

<%= form_with(model: @recipe_food, method: :post) do |form| %>
  <div class="field">
    <%= form.label :recipe_id %>
    <%= form.select :recipe_id, @recipes.map { |recipe_item| [recipe_item.name, recipe_item.id] } %>
  </div>

  <div class="field">
    <%= form.label :food_id, style: "display: block", class: "label" %>
    <%= form.select :food_id, @foods.map { |food| [food.name, food.id] } %>
  </div>

  <div class="field">
    <%= form.label :quantity, style: "display: block", class: "label" %>
    <%= form.number_field :quantity, required: true, class:"input" %>
  </div>

  <div>
    <%= form.submit class: "btn-submit" %>
  </div>
<% end %>

app/views/users/index.html.erb
<section class="container mt-5">
  <h1 class="display-4 text-center mb-4">User List</h1>
  <ul class="list-group">
    <% @users.each do |user| %>
      <li class="list-group-item">
        <%= link_to user.name, foods_path(user_id: user.id), class: "list-group-item-action" %>
      </li>
    <% end %>
  </ul>

</section>